// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: CookingApp_Project

#include "../ui.h"

void ui_HomeScreen_screen_init(void)
{
    ui_HomeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HomeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Keyboard3 = lv_keyboard_create(ui_HomeScreen);
    lv_obj_set_width(ui_Keyboard3, 450);
    lv_obj_set_height(ui_Keyboard3, 180);
    lv_obj_set_x(ui_Keyboard3, 1);
    lv_obj_set_y(ui_Keyboard3, 136);
    lv_obj_set_align(ui_Keyboard3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard3, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_Container1 = lv_obj_create(ui_HomeScreen);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 800);
    lv_obj_set_height(ui_Container1, 50);
    lv_obj_set_x(ui_Container1, 0);
    lv_obj_set_y(ui_Container1, -215);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container1, lv_color_hex(0xB8B8B8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -280);
    lv_obj_set_y(ui_Label2, -150);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Favourites");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FavouriteTile1 = lv_imgbtn_create(ui_HomeScreen);
    lv_imgbtn_set_src(ui_FavouriteTile1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_curry100_png, NULL);
    lv_imgbtn_set_src(ui_FavouriteTile1, LV_IMGBTN_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_FavouriteTile1, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_FavouriteTile1, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_FavouriteTile1, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_FavouriteTile1, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_FavouriteTile1, 100);
    lv_obj_set_height(ui_FavouriteTile1, 100);
    lv_obj_set_x(ui_FavouriteTile1, -302);
    lv_obj_set_y(ui_FavouriteTile1, -60);
    lv_obj_set_align(ui_FavouriteTile1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_FavouriteTile1, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_FavouriteTile1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_FavouriteTile1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_FavouriteTile1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_FavouriteTile1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FavouriteTile2 = lv_imgbtn_create(ui_HomeScreen);
    lv_imgbtn_set_src(ui_FavouriteTile2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_burger100_png, NULL);
    lv_imgbtn_set_src(ui_FavouriteTile2, LV_IMGBTN_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_FavouriteTile2, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_FavouriteTile2, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_FavouriteTile2, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_FavouriteTile2, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_FavouriteTile2, 100);
    lv_obj_set_height(ui_FavouriteTile2, 100);
    lv_obj_set_x(ui_FavouriteTile2, -152);
    lv_obj_set_y(ui_FavouriteTile2, -60);
    lv_obj_set_align(ui_FavouriteTile2, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_FavouriteTile2, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_FavouriteTile2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_FavouriteTile2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_FavouriteTile2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_FavouriteTile2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FavouriteTile3 = lv_imgbtn_create(ui_HomeScreen);
    lv_imgbtn_set_src(ui_FavouriteTile3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_beans100_png, NULL);
    lv_imgbtn_set_src(ui_FavouriteTile3, LV_IMGBTN_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_FavouriteTile3, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_FavouriteTile3, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_FavouriteTile3, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_FavouriteTile3, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_FavouriteTile3, 100);
    lv_obj_set_height(ui_FavouriteTile3, 100);
    lv_obj_set_x(ui_FavouriteTile3, 0);
    lv_obj_set_y(ui_FavouriteTile3, -60);
    lv_obj_set_align(ui_FavouriteTile3, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_FavouriteTile3, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_FavouriteTile3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_FavouriteTile3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_FavouriteTile3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_FavouriteTile3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FavouriteTile4 = lv_imgbtn_create(ui_HomeScreen);
    lv_imgbtn_set_src(ui_FavouriteTile4, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_bol100_png, NULL);
    lv_imgbtn_set_src(ui_FavouriteTile4, LV_IMGBTN_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_FavouriteTile4, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_FavouriteTile4, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_FavouriteTile4, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_FavouriteTile4, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_FavouriteTile4, 100);
    lv_obj_set_height(ui_FavouriteTile4, 100);
    lv_obj_set_x(ui_FavouriteTile4, 152);
    lv_obj_set_y(ui_FavouriteTile4, -60);
    lv_obj_set_align(ui_FavouriteTile4, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_FavouriteTile4, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_FavouriteTile4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_FavouriteTile4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_FavouriteTile4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_FavouriteTile4, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FavouriteTile5 = lv_imgbtn_create(ui_HomeScreen);
    lv_imgbtn_set_src(ui_FavouriteTile5, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_dot100_png, NULL);
    lv_imgbtn_set_src(ui_FavouriteTile5, LV_IMGBTN_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_FavouriteTile5, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_FavouriteTile5, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_FavouriteTile5, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_FavouriteTile5, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_FavouriteTile5, 100);
    lv_obj_set_height(ui_FavouriteTile5, 100);
    lv_obj_set_x(ui_FavouriteTile5, 302);
    lv_obj_set_y(ui_FavouriteTile5, -60);
    lv_obj_set_align(ui_FavouriteTile5, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_FavouriteTile5, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_FavouriteTile5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_FavouriteTile5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_FavouriteTile5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_FavouriteTile5, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FavouriteTitle1 = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_FavouriteTitle1, 110);
    lv_obj_set_height(ui_FavouriteTitle1, 64);
    lv_obj_set_x(ui_FavouriteTitle1, -300);
    lv_obj_set_y(ui_FavouriteTitle1, 35);
    lv_obj_set_align(ui_FavouriteTitle1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FavouriteTitle1, "Yummy curry");
    lv_obj_set_style_text_align(ui_FavouriteTitle1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FavouriteTitle2 = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_FavouriteTitle2, 110);
    lv_obj_set_height(ui_FavouriteTitle2, 64);
    lv_obj_set_x(ui_FavouriteTitle2, -150);
    lv_obj_set_y(ui_FavouriteTitle2, 35);
    lv_obj_set_align(ui_FavouriteTitle2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FavouriteTitle2, "Burger");
    lv_obj_set_style_text_align(ui_FavouriteTitle2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FavouriteTitle3 = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_FavouriteTitle3, 110);
    lv_obj_set_height(ui_FavouriteTitle3, 64);
    lv_obj_set_x(ui_FavouriteTitle3, 0);
    lv_obj_set_y(ui_FavouriteTitle3, 35);
    lv_obj_set_align(ui_FavouriteTitle3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FavouriteTitle3, "Beans on Toast");
    lv_obj_set_style_text_align(ui_FavouriteTitle3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FavouriteTitle4 = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_FavouriteTitle4, 110);
    lv_obj_set_height(ui_FavouriteTitle4, 64);
    lv_obj_set_x(ui_FavouriteTitle4, 150);
    lv_obj_set_y(ui_FavouriteTitle4, 35);
    lv_obj_set_align(ui_FavouriteTitle4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FavouriteTitle4, "Spaghetti Bolognese");
    lv_obj_set_style_text_align(ui_FavouriteTitle4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FavouriteTitle5 = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_FavouriteTitle5, 110);
    lv_obj_set_height(ui_FavouriteTitle5, 64);
    lv_obj_set_x(ui_FavouriteTitle5, 300);
    lv_obj_set_y(ui_FavouriteTitle5, 35);
    lv_obj_set_align(ui_FavouriteTitle5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FavouriteTitle5, "All favourites");
    lv_obj_set_style_text_align(ui_FavouriteTitle5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Divider = lv_obj_create(ui_HomeScreen);
    lv_obj_remove_style_all(ui_Divider);
    lv_obj_set_width(ui_Divider, 700);
    lv_obj_set_height(ui_Divider, 1);
    lv_obj_set_x(ui_Divider, 0);
    lv_obj_set_y(ui_Divider, 79);
    lv_obj_set_align(ui_Divider, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Divider, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Divider, lv_color_hex(0xA0A0A0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Divider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Divider, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Divider1 = lv_obj_create(ui_HomeScreen);
    lv_obj_remove_style_all(ui_Divider1);
    lv_obj_set_width(ui_Divider1, 1);
    lv_obj_set_height(ui_Divider1, 120);
    lv_obj_set_x(ui_Divider1, 0);
    lv_obj_set_y(ui_Divider1, 160);
    lv_obj_set_align(ui_Divider1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Divider1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Divider1, lv_color_hex(0xA0A0A0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Divider1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Divider1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RandomRecipeButton = lv_btn_create(ui_HomeScreen);
    lv_obj_set_width(ui_RandomRecipeButton, 200);
    lv_obj_set_height(ui_RandomRecipeButton, 80);
    lv_obj_set_x(ui_RandomRecipeButton, -200);
    lv_obj_set_y(ui_RandomRecipeButton, 180);
    lv_obj_set_align(ui_RandomRecipeButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RandomRecipeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_RandomRecipeButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RandomRecipeButton, lv_color_hex(0x00C118), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RandomRecipeButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_RandomRecipeButton);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Random recipe");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -200);
    lv_obj_set_y(ui_Label3, 110);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Can't decide what to make?");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrowseButton = lv_btn_create(ui_HomeScreen);
    lv_obj_set_width(ui_BrowseButton, 200);
    lv_obj_set_height(ui_BrowseButton, 80);
    lv_obj_set_x(ui_BrowseButton, 200);
    lv_obj_set_y(ui_BrowseButton, 180);
    lv_obj_set_align(ui_BrowseButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BrowseButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BrowseButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BrowseButton, lv_color_hex(0x00C118), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrowseButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_BrowseButton);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Browse all recipes");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 200);
    lv_obj_set_y(ui_Label7, 110);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Want a new recipe?");
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeTabButton = lv_btn_create(ui_HomeScreen);
    lv_obj_set_width(ui_HomeTabButton, 140);
    lv_obj_set_height(ui_HomeTabButton, 50);
    lv_obj_set_x(ui_HomeTabButton, -330);
    lv_obj_set_y(ui_HomeTabButton, -215);
    lv_obj_set_align(ui_HomeTabButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeTabButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HomeTabButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HomeTabButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HomeTabButton, lv_color_hex(0x59C1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeTabButton, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_HomeTabButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_HomeTabButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeLabel = lv_label_create(ui_HomeTabButton);
    lv_obj_set_width(ui_HomeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HomeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeLabel, "Home");
    lv_obj_set_style_text_color(ui_HomeLabel, lv_color_hex(0x0088FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SelectedLabel = lv_obj_create(ui_HomeTabButton);
    lv_obj_remove_style_all(ui_SelectedLabel);
    lv_obj_set_width(ui_SelectedLabel, 140);
    lv_obj_set_height(ui_SelectedLabel, 4);
    lv_obj_set_x(ui_SelectedLabel, 0);
    lv_obj_set_y(ui_SelectedLabel, 23);
    lv_obj_set_align(ui_SelectedLabel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SelectedLabel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SelectedLabel, lv_color_hex(0x0088FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SelectedLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrowseTabButton = lv_btn_create(ui_HomeScreen);
    lv_obj_set_width(ui_BrowseTabButton, 140);
    lv_obj_set_height(ui_BrowseTabButton, 50);
    lv_obj_set_x(ui_BrowseTabButton, -190);
    lv_obj_set_y(ui_BrowseTabButton, -215);
    lv_obj_set_align(ui_BrowseTabButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BrowseTabButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BrowseTabButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BrowseTabButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BrowseTabButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrowseTabButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BrowseTabButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BrowseTabButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrowseLabel = lv_label_create(ui_BrowseTabButton);
    lv_obj_set_width(ui_BrowseLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BrowseLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BrowseLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BrowseLabel, "Browse");
    lv_obj_set_style_text_color(ui_BrowseLabel, lv_color_hex(0x110700), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BrowseLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BrowseLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ShoppingTabButton = lv_btn_create(ui_HomeScreen);
    lv_obj_set_width(ui_ShoppingTabButton, 140);
    lv_obj_set_height(ui_ShoppingTabButton, 50);
    lv_obj_set_x(ui_ShoppingTabButton, -50);
    lv_obj_set_y(ui_ShoppingTabButton, -215);
    lv_obj_set_align(ui_ShoppingTabButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ShoppingTabButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ShoppingTabButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ShoppingTabButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ShoppingTabButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ShoppingTabButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ShoppingTabButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ShoppingTabButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ShoppingLabel5 = lv_label_create(ui_ShoppingTabButton);
    lv_obj_set_width(ui_ShoppingLabel5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ShoppingLabel5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ShoppingLabel5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ShoppingLabel5, "Shopping List");
    lv_obj_set_style_text_color(ui_ShoppingLabel5, lv_color_hex(0x110700), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ShoppingLabel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ShoppingLabel5, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_FavouriteTile1, ui_event_FavouriteTile1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RandomRecipeButton, ui_event_RandomRecipeButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BrowseTabButton, ui_event_BrowseTabButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ShoppingTabButton, ui_event_ShoppingTabButton, LV_EVENT_ALL, NULL);

}
