// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: CookingApp_Project

#include "../ui.h"

void ui_SettingsScreen_screen_init(void)
{
    ui_SettingsScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SettingsScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Keyboard8 = lv_keyboard_create(ui_SettingsScreen);
    lv_obj_set_width(ui_Keyboard8, 450);
    lv_obj_set_height(ui_Keyboard8, 180);
    lv_obj_set_x(ui_Keyboard8, 1);
    lv_obj_set_y(ui_Keyboard8, 136);
    lv_obj_set_align(ui_Keyboard8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard8, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_Container6 = lv_obj_create(ui_SettingsScreen);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, 800);
    lv_obj_set_height(ui_Container6, 50);
    lv_obj_set_x(ui_Container6, 0);
    lv_obj_set_y(ui_Container6, -215);
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container6, lv_color_hex(0xB8B8B8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_Label17, 600);
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 280
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17,
                      "Boil the potatoes in a pan of salted water for eight minutes until just tender, then drain well. ");
    lv_obj_set_style_text_align(ui_Label17, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NextStepButton1 = lv_btn_create(ui_SettingsScreen);
    lv_obj_set_width(ui_NextStepButton1, 60);
    lv_obj_set_height(ui_NextStepButton1, 60);
    lv_obj_set_x(ui_NextStepButton1, 360);
    lv_obj_set_y(ui_NextStepButton1, 0);
    lv_obj_set_align(ui_NextStepButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NextStepButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_NextStepButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_NextStepButton1, lv_color_hex(0x00C118), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NextStepButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_NextStepButton1);
    lv_img_set_src(ui_Image3, &ui_img_arrow_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_Image3, 900);

    ui_PreviousStepButton1 = lv_btn_create(ui_SettingsScreen);
    lv_obj_set_width(ui_PreviousStepButton1, 60);
    lv_obj_set_height(ui_PreviousStepButton1, 60);
    lv_obj_set_x(ui_PreviousStepButton1, -360);
    lv_obj_set_y(ui_PreviousStepButton1, 0);
    lv_obj_set_align(ui_PreviousStepButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PreviousStepButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PreviousStepButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PreviousStepButton1, lv_color_hex(0x00C118), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PreviousStepButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_PreviousStepButton1);
    lv_img_set_src(ui_Image4, &ui_img_arrow_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_Image4, 2700);

    ui_ShoppingTabButton5 = lv_btn_create(ui_SettingsScreen);
    lv_obj_set_width(ui_ShoppingTabButton5, 140);
    lv_obj_set_height(ui_ShoppingTabButton5, 50);
    lv_obj_set_x(ui_ShoppingTabButton5, -50);
    lv_obj_set_y(ui_ShoppingTabButton5, -215);
    lv_obj_set_align(ui_ShoppingTabButton5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ShoppingTabButton5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ShoppingTabButton5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ShoppingTabButton5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ShoppingTabButton5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ShoppingTabButton5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ShoppingTabButton5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ShoppingTabButton5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ShoppingLabel1 = lv_label_create(ui_ShoppingTabButton5);
    lv_obj_set_width(ui_ShoppingLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ShoppingLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ShoppingLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ShoppingLabel1, "Shopping List");
    lv_obj_set_style_text_color(ui_ShoppingLabel1, lv_color_hex(0x110700), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ShoppingLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ShoppingLabel1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrowseTabButton2 = lv_btn_create(ui_SettingsScreen);
    lv_obj_set_width(ui_BrowseTabButton2, 140);
    lv_obj_set_height(ui_BrowseTabButton2, 50);
    lv_obj_set_x(ui_BrowseTabButton2, -190);
    lv_obj_set_y(ui_BrowseTabButton2, -215);
    lv_obj_set_align(ui_BrowseTabButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BrowseTabButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BrowseTabButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BrowseTabButton2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BrowseTabButton2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrowseTabButton2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BrowseTabButton2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BrowseTabButton2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrowseLabel4 = lv_label_create(ui_BrowseTabButton2);
    lv_obj_set_width(ui_BrowseLabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BrowseLabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BrowseLabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BrowseLabel4, "Browse");
    lv_obj_set_style_text_color(ui_BrowseLabel4, lv_color_hex(0x110700), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BrowseLabel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BrowseLabel4, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeTabButton2 = lv_btn_create(ui_SettingsScreen);
    lv_obj_set_width(ui_HomeTabButton2, 140);
    lv_obj_set_height(ui_HomeTabButton2, 50);
    lv_obj_set_x(ui_HomeTabButton2, -330);
    lv_obj_set_y(ui_HomeTabButton2, -215);
    lv_obj_set_align(ui_HomeTabButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeTabButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HomeTabButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HomeTabButton2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HomeTabButton2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeTabButton2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_HomeTabButton2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_HomeTabButton2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeLabel2 = lv_label_create(ui_HomeTabButton2);
    lv_obj_set_width(ui_HomeLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HomeLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeLabel2, "Home");
    lv_obj_set_style_text_color(ui_HomeLabel2, lv_color_hex(0x110700), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeLabel2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsButton6 = lv_btn_create(ui_SettingsScreen);
    lv_obj_set_width(ui_SettingsButton6, 50);
    lv_obj_set_height(ui_SettingsButton6, 50);
    lv_obj_set_x(ui_SettingsButton6, 310);
    lv_obj_set_y(ui_SettingsButton6, -215);
    lv_obj_set_align(ui_SettingsButton6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingsButton6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SettingsButton6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SettingsButton6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingsButton6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SettingsButton6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SettingsButton6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsImage6 = lv_img_create(ui_SettingsButton6);
    lv_img_set_src(ui_SettingsImage6, &ui_img_settings_png);
    lv_obj_set_width(ui_SettingsImage6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsImage6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingsImage6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingsImage6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SettingsImage6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_SettingsImage6, 180);

    ui_WifiButton6 = lv_btn_create(ui_SettingsScreen);
    lv_obj_set_width(ui_WifiButton6, 50);
    lv_obj_set_height(ui_WifiButton6, 50);
    lv_obj_set_x(ui_WifiButton6, 250);
    lv_obj_set_y(ui_WifiButton6, -215);
    lv_obj_set_align(ui_WifiButton6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiButton6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WifiButton6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WifiButton6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiButton6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_WifiButton6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_WifiButton6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiImage6 = lv_img_create(ui_WifiButton6);
    lv_img_set_src(ui_WifiImage6, &ui_img_wifi_png);
    lv_obj_set_width(ui_WifiImage6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiImage6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WifiImage6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiImage6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WifiImage6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PowerButton6 = lv_btn_create(ui_SettingsScreen);
    lv_obj_set_width(ui_PowerButton6, 50);
    lv_obj_set_height(ui_PowerButton6, 50);
    lv_obj_set_x(ui_PowerButton6, 370);
    lv_obj_set_y(ui_PowerButton6, -215);
    lv_obj_set_align(ui_PowerButton6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PowerButton6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PowerButton6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PowerButton6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PowerButton6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_PowerButton6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_PowerButton6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PowerImage6 = lv_img_create(ui_PowerButton6);
    lv_img_set_src(ui_PowerImage6, &ui_img_power_png);
    lv_obj_set_width(ui_PowerImage6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PowerImage6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PowerImage6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PowerImage6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PowerImage6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_ShoppingTabButton5, ui_event_ShoppingTabButton5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BrowseTabButton2, ui_event_BrowseTabButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HomeTabButton2, ui_event_HomeTabButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SettingsButton6, ui_event_SettingsButton6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WifiButton6, ui_event_WifiButton6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PowerButton6, ui_event_PowerButton6, LV_EVENT_ALL, NULL);

}
