// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: CookingApp_Project

#include "../ui.h"

void ui_ShoppingScreen_screen_init(void)
{
    ui_ShoppingScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ShoppingScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container3 = lv_obj_create(ui_ShoppingScreen);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 800);
    lv_obj_set_height(ui_Container3, 50);
    lv_obj_set_x(ui_Container3, 0);
    lv_obj_set_y(ui_Container3, -215);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container3, lv_color_hex(0xB8B8B8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_ShoppingScreen);
    lv_obj_set_width(ui_Label10, 200);
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 200);
    lv_obj_set_y(ui_Label10, 150);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Clear items");
    lv_obj_set_style_text_align(ui_Label10, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_ShoppingScreen);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -235);
    lv_obj_set_y(ui_Label9, -150);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Shopping Items");
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AddToShoppingListButton1 = lv_btn_create(ui_ShoppingScreen);
    lv_obj_set_width(ui_AddToShoppingListButton1, 100);
    lv_obj_set_height(ui_AddToShoppingListButton1, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_AddToShoppingListButton1, 200);
    lv_obj_set_y(ui_AddToShoppingListButton1, 190);
    lv_obj_set_align(ui_AddToShoppingListButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AddToShoppingListButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_AddToShoppingListButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AddToShoppingListButton1, lv_color_hex(0x00C118), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AddToShoppingListButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_AddToShoppingListButton1);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Clear list");

    ui_ShoppingListText = lv_label_create(ui_ShoppingScreen);
    lv_obj_set_width(ui_ShoppingListText, 400);
    lv_obj_set_height(ui_ShoppingListText, 300);
    lv_obj_set_x(ui_ShoppingListText, -155);
    lv_obj_set_y(ui_ShoppingListText, 30);
    lv_obj_set_align(ui_ShoppingListText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ShoppingListText, "• Eggs		\n• Green Ham\n• Bread\n");
    lv_obj_set_style_text_font(ui_ShoppingListText, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Divider2 = lv_obj_create(ui_ShoppingScreen);
    lv_obj_remove_style_all(ui_Divider2);
    lv_obj_set_width(ui_Divider2, 1);
    lv_obj_set_height(ui_Divider2, 400);
    lv_obj_set_x(ui_Divider2, 0);
    lv_obj_set_y(ui_Divider2, 25);
    lv_obj_set_align(ui_Divider2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Divider2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Divider2, lv_color_hex(0xA0A0A0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Divider2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AddToShoppingListField = lv_textarea_create(ui_ShoppingScreen);
    lv_obj_set_width(ui_AddToShoppingListField, 250);
    lv_obj_set_height(ui_AddToShoppingListField, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_AddToShoppingListField, 150);
    lv_obj_set_y(ui_AddToShoppingListField, -110);
    lv_obj_set_align(ui_AddToShoppingListField, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_AddToShoppingListField, "Placeholder...");
    lv_textarea_set_one_line(ui_AddToShoppingListField, true);



    ui_Keyboard5 = lv_keyboard_create(ui_ShoppingScreen);
    lv_obj_set_width(ui_Keyboard5, 450);
    lv_obj_set_height(ui_Keyboard5, 180);
    lv_obj_set_x(ui_Keyboard5, 1);
    lv_obj_set_y(ui_Keyboard5, 136);
    lv_obj_set_align(ui_Keyboard5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard5, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_color(ui_Keyboard5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Keyboard5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_ShoppingScreen);
    lv_obj_set_width(ui_Label11, 200);
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 200);
    lv_obj_set_y(ui_Label11, -150);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Add items");
    lv_obj_set_style_text_align(ui_Label11, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AddToShoppingListButton = lv_btn_create(ui_ShoppingScreen);
    lv_obj_set_width(ui_AddToShoppingListButton, 80);
    lv_obj_set_height(ui_AddToShoppingListButton, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_AddToShoppingListButton, 330);
    lv_obj_set_y(ui_AddToShoppingListButton, -110);
    lv_obj_set_align(ui_AddToShoppingListButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AddToShoppingListButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_AddToShoppingListButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AddToShoppingListButton, lv_color_hex(0x00C118), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AddToShoppingListButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_AddToShoppingListButton);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Add");

    ui_BrowseTabButton3 = lv_btn_create(ui_ShoppingScreen);
    lv_obj_set_width(ui_BrowseTabButton3, 140);
    lv_obj_set_height(ui_BrowseTabButton3, 50);
    lv_obj_set_x(ui_BrowseTabButton3, -190);
    lv_obj_set_y(ui_BrowseTabButton3, -215);
    lv_obj_set_align(ui_BrowseTabButton3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BrowseTabButton3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BrowseTabButton3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BrowseTabButton3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BrowseTabButton3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrowseTabButton3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BrowseTabButton3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BrowseTabButton3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrowseLabel5 = lv_label_create(ui_BrowseTabButton3);
    lv_obj_set_width(ui_BrowseLabel5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BrowseLabel5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BrowseLabel5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BrowseLabel5, "Browse");
    lv_obj_set_style_text_color(ui_BrowseLabel5, lv_color_hex(0x110700), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BrowseLabel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BrowseLabel5, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeTabButton3 = lv_btn_create(ui_ShoppingScreen);
    lv_obj_set_width(ui_HomeTabButton3, 140);
    lv_obj_set_height(ui_HomeTabButton3, 50);
    lv_obj_set_x(ui_HomeTabButton3, -330);
    lv_obj_set_y(ui_HomeTabButton3, -215);
    lv_obj_set_align(ui_HomeTabButton3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeTabButton3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HomeTabButton3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HomeTabButton3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HomeTabButton3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeTabButton3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_HomeTabButton3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_HomeTabButton3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeLabel3 = lv_label_create(ui_HomeTabButton3);
    lv_obj_set_width(ui_HomeLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HomeLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeLabel3, "Home");
    lv_obj_set_style_text_color(ui_HomeLabel3, lv_color_hex(0x110700), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeLabel3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ShoppingTabButton1 = lv_btn_create(ui_ShoppingScreen);
    lv_obj_set_width(ui_ShoppingTabButton1, 140);
    lv_obj_set_height(ui_ShoppingTabButton1, 50);
    lv_obj_set_x(ui_ShoppingTabButton1, -50);
    lv_obj_set_y(ui_ShoppingTabButton1, -215);
    lv_obj_set_align(ui_ShoppingTabButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ShoppingTabButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ShoppingTabButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ShoppingTabButton1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ShoppingTabButton1, lv_color_hex(0x59C1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ShoppingTabButton1, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ShoppingTabButton1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ShoppingTabButton1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ShoppingLabel = lv_label_create(ui_ShoppingTabButton1);
    lv_obj_set_width(ui_ShoppingLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ShoppingLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ShoppingLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ShoppingLabel, "Shopping List");
    lv_obj_set_style_text_color(ui_ShoppingLabel, lv_color_hex(0x0088FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ShoppingLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ShoppingLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SelectedLabel3 = lv_obj_create(ui_ShoppingTabButton1);
    lv_obj_remove_style_all(ui_SelectedLabel3);
    lv_obj_set_width(ui_SelectedLabel3, 140);
    lv_obj_set_height(ui_SelectedLabel3, 4);
    lv_obj_set_x(ui_SelectedLabel3, 0);
    lv_obj_set_y(ui_SelectedLabel3, 23);
    lv_obj_set_align(ui_SelectedLabel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SelectedLabel3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SelectedLabel3, lv_color_hex(0x0088FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SelectedLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsButton3 = lv_btn_create(ui_ShoppingScreen);
    lv_obj_set_width(ui_SettingsButton3, 50);
    lv_obj_set_height(ui_SettingsButton3, 50);
    lv_obj_set_x(ui_SettingsButton3, 310);
    lv_obj_set_y(ui_SettingsButton3, -215);
    lv_obj_set_align(ui_SettingsButton3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingsButton3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SettingsButton3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SettingsButton3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingsButton3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SettingsButton3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SettingsButton3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsImage3 = lv_img_create(ui_SettingsButton3);
    lv_img_set_src(ui_SettingsImage3, &ui_img_settings_png);
    lv_obj_set_width(ui_SettingsImage3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsImage3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingsImage3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingsImage3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SettingsImage3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_SettingsImage3, 180);

    ui_WifiButton3 = lv_btn_create(ui_ShoppingScreen);
    lv_obj_set_width(ui_WifiButton3, 50);
    lv_obj_set_height(ui_WifiButton3, 50);
    lv_obj_set_x(ui_WifiButton3, 250);
    lv_obj_set_y(ui_WifiButton3, -215);
    lv_obj_set_align(ui_WifiButton3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiButton3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WifiButton3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WifiButton3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiButton3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_WifiButton3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_WifiButton3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiImage3 = lv_img_create(ui_WifiButton3);
    lv_img_set_src(ui_WifiImage3, &ui_img_wifi_png);
    lv_obj_set_width(ui_WifiImage3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiImage3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WifiImage3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiImage3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WifiImage3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PowerButton3 = lv_btn_create(ui_ShoppingScreen);
    lv_obj_set_width(ui_PowerButton3, 50);
    lv_obj_set_height(ui_PowerButton3, 50);
    lv_obj_set_x(ui_PowerButton3, 370);
    lv_obj_set_y(ui_PowerButton3, -215);
    lv_obj_set_align(ui_PowerButton3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PowerButton3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PowerButton3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PowerButton3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PowerButton3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_PowerButton3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_PowerButton3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PowerImage3 = lv_img_create(ui_PowerButton3);
    lv_img_set_src(ui_PowerImage3, &ui_img_power_png);
    lv_obj_set_width(ui_PowerImage3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PowerImage3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PowerImage3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PowerImage3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PowerImage3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_AddToShoppingListField, ui_event_AddToShoppingListField, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BrowseTabButton3, ui_event_BrowseTabButton3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HomeTabButton3, ui_event_HomeTabButton3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SettingsButton3, ui_event_SettingsButton3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WifiButton3, ui_event_WifiButton3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PowerButton3, ui_event_PowerButton3, LV_EVENT_ALL, NULL);

}
