// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: CookingApp_Project

#include "../ui.h"

void ui_WelcomeScreen_screen_init(void)
{
    ui_WelcomeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_WelcomeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Keyboard2 = lv_keyboard_create(ui_WelcomeScreen);
    lv_obj_set_width(ui_Keyboard2, 450);
    lv_obj_set_height(ui_Keyboard2, 180);
    lv_obj_set_x(ui_Keyboard2, 1);
    lv_obj_set_y(ui_Keyboard2, 136);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_Welcome = lv_label_create(ui_WelcomeScreen);
    lv_obj_set_width(ui_Welcome, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Welcome, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Welcome, 0);
    lv_obj_set_y(ui_Welcome, -200);
    lv_obj_set_align(ui_Welcome, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Welcome, "Welcome!");
    lv_obj_set_style_text_font(ui_Welcome, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StartClock = lv_label_create(ui_WelcomeScreen);
    lv_obj_set_width(ui_StartClock, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StartClock, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StartClock, 0);
    lv_obj_set_y(ui_StartClock, -50);
    lv_obj_set_align(ui_StartClock, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StartClock, "00:00");
    lv_obj_set_style_text_align(ui_StartClock, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StartClock, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_WelcomeScreen);
    lv_obj_set_width(ui_Button1, 200);
    lv_obj_set_height(ui_Button1, 80);
    lv_obj_set_x(ui_Button1, 0);
    lv_obj_set_y(ui_Button1, 80);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x00C118), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Lets cook!");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);

}
