// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: CookingApp_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_WelcomeScreen
void ui_WelcomeScreen_screen_init(void);
lv_obj_t * ui_WelcomeScreen;
lv_obj_t * ui_Keyboard2;
lv_obj_t * ui_Welcome;
lv_obj_t * ui_StartClock;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label4;


// SCREEN: ui_WifiScreen
void ui_WifiScreen_screen_init(void);
lv_obj_t * ui_WifiScreen;
void ui_event_SSID(lv_event_t * e);
lv_obj_t * ui_SSID;
void ui_event_Password(lv_event_t * e);
lv_obj_t * ui_Password;
lv_obj_t * ui_Status;
void ui_event_Connect(lv_event_t * e);
lv_obj_t * ui_Connect;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Keyboard1;
lv_obj_t * ui_Container8;
void ui_event_HomeTabButton7(lv_event_t * e);
lv_obj_t * ui_HomeTabButton7;
lv_obj_t * ui_HomeLabel7;
void ui_event_BrowseTabButton7(lv_event_t * e);
lv_obj_t * ui_BrowseTabButton7;
lv_obj_t * ui_BrowseLabel7;
void ui_event_ShoppingTabButton7(lv_event_t * e);
lv_obj_t * ui_ShoppingTabButton7;
lv_obj_t * ui_ShoppingLabel7;
void ui_event_SettingsButton7(lv_event_t * e);
lv_obj_t * ui_SettingsButton7;
lv_obj_t * ui_SettingsImage7;
void ui_event_WifiButton7(lv_event_t * e);
lv_obj_t * ui_WifiButton7;
lv_obj_t * ui_WifiImage7;
void ui_event_PowerButton7(lv_event_t * e);
lv_obj_t * ui_PowerButton7;
lv_obj_t * ui_PowerImage7;


// SCREEN: ui_HomeScreen
void ui_HomeScreen_screen_init(void);
lv_obj_t * ui_HomeScreen;
lv_obj_t * ui_Keyboard3;
lv_obj_t * ui_Container1;
lv_obj_t * ui_Label2;
void ui_event_FavouriteTile1(lv_event_t * e);
lv_obj_t * ui_FavouriteTile1;
lv_obj_t * ui_FavouriteTile2;
lv_obj_t * ui_FavouriteTile3;
lv_obj_t * ui_FavouriteTile4;
lv_obj_t * ui_FavouriteTile5;
lv_obj_t * ui_FavouriteTitle1;
lv_obj_t * ui_FavouriteTitle2;
lv_obj_t * ui_FavouriteTitle3;
lv_obj_t * ui_FavouriteTitle4;
lv_obj_t * ui_FavouriteTitle5;
lv_obj_t * ui_Divider;
lv_obj_t * ui_Divider1;
void ui_event_RandomRecipeButton(lv_event_t * e);
lv_obj_t * ui_RandomRecipeButton;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label3;
void ui_event_BrowseButton(lv_event_t * e);
lv_obj_t * ui_BrowseButton;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Label7;
lv_obj_t * ui_HomeTabButton;
lv_obj_t * ui_HomeLabel;
lv_obj_t * ui_SelectedLabel;
void ui_event_BrowseTabButton(lv_event_t * e);
lv_obj_t * ui_BrowseTabButton;
lv_obj_t * ui_BrowseLabel;
void ui_event_PowerButton5(lv_event_t * e);
lv_obj_t * ui_PowerButton5;
lv_obj_t * ui_PowerImage5;
void ui_event_ShoppingTabButton(lv_event_t * e);
lv_obj_t * ui_ShoppingTabButton;
lv_obj_t * ui_ShoppingLabel5;
void ui_event_WifiButton5(lv_event_t * e);
lv_obj_t * ui_WifiButton5;
lv_obj_t * ui_WifiImage5;
void ui_event_SettingsButton5(lv_event_t * e);
lv_obj_t * ui_SettingsButton5;
lv_obj_t * ui_SettingsImage5;


// SCREEN: ui_BrowseScreen
void ui_BrowseScreen_screen_init(void);
lv_obj_t * ui_BrowseScreen;
lv_obj_t * ui_Keyboard4;
lv_obj_t * ui_Container2;
lv_obj_t * ui_Label8;
void ui_event_FavouriteTile6(lv_event_t * e);
lv_obj_t * ui_FavouriteTile6;
lv_obj_t * ui_FavouriteTile7;
lv_obj_t * ui_FavouriteTile8;
lv_obj_t * ui_FavouriteTile9;
lv_obj_t * ui_FavouriteTile10;
lv_obj_t * ui_FavouriteTitle6;
lv_obj_t * ui_FavouriteTitle7;
lv_obj_t * ui_FavouriteTitle8;
lv_obj_t * ui_FavouriteTitle9;
lv_obj_t * ui_FavouriteTitle10;
lv_obj_t * ui_FavouriteTile11;
lv_obj_t * ui_FavouriteTile12;
lv_obj_t * ui_FavouriteTile13;
lv_obj_t * ui_FavouriteTile14;
lv_obj_t * ui_FavouriteTile15;
lv_obj_t * ui_BrowseTabButton1;
lv_obj_t * ui_BrowseLabel1;
lv_obj_t * ui_SelectedLabel1;
void ui_event_HomeTabButton1(lv_event_t * e);
lv_obj_t * ui_HomeTabButton1;
lv_obj_t * ui_HomeLabel1;
void ui_event_ShoppingTabButton2(lv_event_t * e);
lv_obj_t * ui_ShoppingTabButton2;
lv_obj_t * ui_ShoppingLabel6;
void ui_event_SettingsButton4(lv_event_t * e);
lv_obj_t * ui_SettingsButton4;
lv_obj_t * ui_SettingsImage4;
void ui_event_WifiButton4(lv_event_t * e);
lv_obj_t * ui_WifiButton4;
lv_obj_t * ui_WifiImage4;
void ui_event_PowerButton4(lv_event_t * e);
lv_obj_t * ui_PowerButton4;
lv_obj_t * ui_PowerImage4;


// SCREEN: ui_ShoppingScreen
void ui_ShoppingScreen_screen_init(void);
lv_obj_t * ui_ShoppingScreen;
lv_obj_t * ui_Container3;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Label9;
lv_obj_t * ui_AddToShoppingListButton1;
lv_obj_t * ui_Label12;
lv_obj_t * ui_ShoppingListText;
lv_obj_t * ui_Divider2;
void ui_event_AddToShoppingListField(lv_event_t * e);
lv_obj_t * ui_AddToShoppingListField;
lv_obj_t * ui_Keyboard5;
lv_obj_t * ui_Label11;
lv_obj_t * ui_AddToShoppingListButton;
lv_obj_t * ui_Label13;
void ui_event_BrowseTabButton3(lv_event_t * e);
lv_obj_t * ui_BrowseTabButton3;
lv_obj_t * ui_BrowseLabel5;
void ui_event_HomeTabButton3(lv_event_t * e);
lv_obj_t * ui_HomeTabButton3;
lv_obj_t * ui_HomeLabel3;
lv_obj_t * ui_ShoppingTabButton1;
lv_obj_t * ui_ShoppingLabel;
lv_obj_t * ui_SelectedLabel3;
void ui_event_SettingsButton3(lv_event_t * e);
lv_obj_t * ui_SettingsButton3;
lv_obj_t * ui_SettingsImage3;
void ui_event_WifiButton3(lv_event_t * e);
lv_obj_t * ui_WifiButton3;
lv_obj_t * ui_WifiImage3;
void ui_event_PowerButton3(lv_event_t * e);
lv_obj_t * ui_PowerButton3;
lv_obj_t * ui_PowerImage3;


// SCREEN: ui_DescriptionScreen
void ui_DescriptionScreen_screen_init(void);
lv_obj_t * ui_DescriptionScreen;
lv_obj_t * ui_Keyboard6;
lv_obj_t * ui_Container4;
lv_obj_t * ui_RecipeTitle;
lv_obj_t * ui_DescriptionText;
lv_obj_t * ui_Divider3;
lv_obj_t * ui_AddToShoppingListButton3;
lv_obj_t * ui_Label18;
lv_obj_t * ui_RecipeImage;
void ui_event_RecipeStartButton(lv_event_t * e);
lv_obj_t * ui_RecipeStartButton;
lv_obj_t * ui_Label14;
lv_obj_t * ui_AddToShoppingListButton2;
lv_obj_t * ui_Label16;
void ui_event_ShoppingTabButton3(lv_event_t * e);
lv_obj_t * ui_ShoppingTabButton3;
lv_obj_t * ui_ShoppingLabel2;
void ui_event_BrowseTabButton4(lv_event_t * e);
lv_obj_t * ui_BrowseTabButton4;
lv_obj_t * ui_BrowseLabel2;
void ui_event_HomeTabButton4(lv_event_t * e);
lv_obj_t * ui_HomeTabButton4;
lv_obj_t * ui_HomeLabel4;
void ui_event_SettingsButton2(lv_event_t * e);
lv_obj_t * ui_SettingsButton2;
lv_obj_t * ui_SettingsImage2;
void ui_event_WifiButton2(lv_event_t * e);
lv_obj_t * ui_WifiButton2;
lv_obj_t * ui_WifiImage2;
void ui_event_PowerButton2(lv_event_t * e);
lv_obj_t * ui_PowerButton2;
lv_obj_t * ui_PowerImage2;


// SCREEN: ui_RecipeScreen
void ui_RecipeScreen_screen_init(void);
lv_obj_t * ui_RecipeScreen;
lv_obj_t * ui_Keyboard7;
lv_obj_t * ui_Container5;
lv_obj_t * ui_Label15;
lv_obj_t * ui_NextStepButton;
lv_obj_t * ui_Image2;
lv_obj_t * ui_PreviousStepButton;
lv_obj_t * ui_Image1;
void ui_event_ShoppingTabButton4(lv_event_t * e);
lv_obj_t * ui_ShoppingTabButton4;
lv_obj_t * ui_ShoppingLabel3;
void ui_event_BrowseTabButton5(lv_event_t * e);
lv_obj_t * ui_BrowseTabButton5;
lv_obj_t * ui_BrowseLabel3;
void ui_event_HomeTabButton5(lv_event_t * e);
lv_obj_t * ui_HomeTabButton5;
lv_obj_t * ui_HomeLabel5;
void ui_event_SettingsButton(lv_event_t * e);
lv_obj_t * ui_SettingsButton;
lv_obj_t * ui_SettingsImage;
void ui_event_WifiButton(lv_event_t * e);
lv_obj_t * ui_WifiButton;
lv_obj_t * ui_WifiImage;
void ui_event_PowerButton(lv_event_t * e);
lv_obj_t * ui_PowerButton;
lv_obj_t * ui_PowerImage;
lv_obj_t * ui_PowerBox;
lv_obj_t * ui_Label19;
void ui_event_GoToStartButton(lv_event_t * e);
lv_obj_t * ui_GoToStartButton;
lv_obj_t * ui_Label21;
lv_obj_t * ui_SleepButton;
lv_obj_t * ui_Label20;
void ui_event_ClosePowerBox(lv_event_t * e);
lv_obj_t * ui_ClosePowerBox;
lv_obj_t * ui_Image5;


// SCREEN: ui_SettingsScreen
void ui_SettingsScreen_screen_init(void);
lv_obj_t * ui_SettingsScreen;
lv_obj_t * ui_Keyboard8;
lv_obj_t * ui_Container6;
lv_obj_t * ui_Label17;
lv_obj_t * ui_NextStepButton1;
lv_obj_t * ui_Image3;
lv_obj_t * ui_PreviousStepButton1;
lv_obj_t * ui_Image4;
void ui_event_ShoppingTabButton5(lv_event_t * e);
lv_obj_t * ui_ShoppingTabButton5;
lv_obj_t * ui_ShoppingLabel1;
void ui_event_BrowseTabButton2(lv_event_t * e);
lv_obj_t * ui_BrowseTabButton2;
lv_obj_t * ui_BrowseLabel4;
void ui_event_HomeTabButton2(lv_event_t * e);
lv_obj_t * ui_HomeTabButton2;
lv_obj_t * ui_HomeLabel2;
void ui_event_SettingsButton6(lv_event_t * e);
lv_obj_t * ui_SettingsButton6;
lv_obj_t * ui_SettingsImage6;
void ui_event_WifiButton6(lv_event_t * e);
lv_obj_t * ui_WifiButton6;
lv_obj_t * ui_WifiImage6;
void ui_event_PowerButton6(lv_event_t * e);
lv_obj_t * ui_PowerButton6;
lv_obj_t * ui_PowerImage6;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_ban[1] = {&ui_img_ban100_png};
const lv_img_dsc_t * ui_imgset_beans[1] = {&ui_img_beans100_png};
const lv_img_dsc_t * ui_imgset_bol[1] = {&ui_img_bol100_png};
const lv_img_dsc_t * ui_imgset_burger[1] = {&ui_img_burger100_png};
const lv_img_dsc_t * ui_imgset_curry[2] = {&ui_img_curry100_png, &ui_img_curry200_png};
const lv_img_dsc_t * ui_imgset_dot[1] = {&ui_img_dot100_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_HomeScreen_screen_init);
    }
}
void ui_event_SSID(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_Keyboard1,  ui_SSID);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_Password(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_Keyboard1,  ui_Password);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_Connect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        on_connect_button_click(e);
    }
}
void ui_event_HomeTabButton7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_HomeScreen_screen_init);
    }
}
void ui_event_BrowseTabButton7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_BrowseScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_BrowseScreen_screen_init);
    }
}
void ui_event_ShoppingTabButton7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ShoppingScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_ShoppingScreen_screen_init);
    }
}
void ui_event_SettingsButton7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingsScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_SettingsScreen_screen_init);
    }
}
void ui_event_WifiButton7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WifiScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_WifiScreen_screen_init);
    }
}
void ui_event_PowerButton7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WelcomeScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_WelcomeScreen_screen_init);
    }
}
void ui_event_FavouriteTile1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_DescriptionScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_DescriptionScreen_screen_init);
    }
}
void ui_event_RandomRecipeButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_DescriptionScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_DescriptionScreen_screen_init);
    }
}
void ui_event_BrowseButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_BrowseScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_BrowseScreen_screen_init);
    }
}
void ui_event_BrowseTabButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_BrowseScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_BrowseScreen_screen_init);
    }
}
void ui_event_PowerButton5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WelcomeScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_WelcomeScreen_screen_init);
    }
}
void ui_event_ShoppingTabButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ShoppingScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_ShoppingScreen_screen_init);
    }
}
void ui_event_WifiButton5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WifiScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_WifiScreen_screen_init);
    }
}
void ui_event_SettingsButton5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingsScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_SettingsScreen_screen_init);
    }
}
void ui_event_FavouriteTile6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_DescriptionScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_DescriptionScreen_screen_init);
    }
}
void ui_event_HomeTabButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_HomeScreen_screen_init);
    }
}
void ui_event_ShoppingTabButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ShoppingScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_ShoppingScreen_screen_init);
    }
}
void ui_event_SettingsButton4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingsScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_SettingsScreen_screen_init);
    }
}
void ui_event_WifiButton4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WifiScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_WifiScreen_screen_init);
    }
}
void ui_event_PowerButton4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WelcomeScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_WelcomeScreen_screen_init);
    }
}
void ui_event_AddToShoppingListField(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard5,  ui_AddToShoppingListField);
        _ui_flag_modify(ui_Keyboard5, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard5, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_BrowseTabButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_BrowseScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_BrowseScreen_screen_init);
    }
}
void ui_event_HomeTabButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_HomeScreen_screen_init);
    }
}
void ui_event_SettingsButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingsScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_SettingsScreen_screen_init);
    }
}
void ui_event_WifiButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WifiScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_WifiScreen_screen_init);
    }
}
void ui_event_PowerButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WelcomeScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_WelcomeScreen_screen_init);
    }
}
void ui_event_RecipeStartButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_RecipeScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_RecipeScreen_screen_init);
    }
}
void ui_event_ShoppingTabButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ShoppingScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_ShoppingScreen_screen_init);
    }
}
void ui_event_BrowseTabButton4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_BrowseScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_BrowseScreen_screen_init);
    }
}
void ui_event_HomeTabButton4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_HomeScreen_screen_init);
    }
}
void ui_event_SettingsButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingsScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_SettingsScreen_screen_init);
    }
}
void ui_event_WifiButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WifiScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_WifiScreen_screen_init);
    }
}
void ui_event_PowerButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WelcomeScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_WelcomeScreen_screen_init);
    }
}
void ui_event_ShoppingTabButton4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ShoppingScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_ShoppingScreen_screen_init);
    }
}
void ui_event_BrowseTabButton5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_BrowseScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_BrowseScreen_screen_init);
    }
}
void ui_event_HomeTabButton5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_HomeScreen_screen_init);
    }
}
void ui_event_SettingsButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingsScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_SettingsScreen_screen_init);
    }
}
void ui_event_WifiButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WifiScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_WifiScreen_screen_init);
    }
}
void ui_event_PowerButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WelcomeScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_WelcomeScreen_screen_init);
    }
}
void ui_event_GoToStartButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WelcomeScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_WelcomeScreen_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_PowerBox, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_ClosePowerBox(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_PowerBox, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_ShoppingTabButton5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ShoppingScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_ShoppingScreen_screen_init);
    }
}
void ui_event_BrowseTabButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_BrowseScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_BrowseScreen_screen_init);
    }
}
void ui_event_HomeTabButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_HomeScreen_screen_init);
    }
}
void ui_event_SettingsButton6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingsScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_SettingsScreen_screen_init);
    }
}
void ui_event_WifiButton6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WifiScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_WifiScreen_screen_init);
    }
}
void ui_event_PowerButton6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WelcomeScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_WelcomeScreen_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_WelcomeScreen_screen_init();
    ui_WifiScreen_screen_init();
    ui_HomeScreen_screen_init();
    ui_BrowseScreen_screen_init();
    ui_ShoppingScreen_screen_init();
    ui_DescriptionScreen_screen_init();
    ui_RecipeScreen_screen_init();
    ui_SettingsScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_WelcomeScreen);
}
