// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: CookingApp_Project

#ifndef _COOKINGAPP_PROJECT_UI_H
#define _COOKINGAPP_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
void ui_event_SSID(lv_event_t * e);
extern lv_obj_t * ui_SSID;
void ui_event_Password(lv_event_t * e);
extern lv_obj_t * ui_Password;
extern lv_obj_t * ui_Status;
void ui_event_Connect(lv_event_t * e);
extern lv_obj_t * ui_Connect;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Keyboard2;
extern lv_obj_t * ui____initial_actions0;








void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
